version: 2.1
orbs:
  php: circleci/php@1.0
workflows:
  deploy:
    jobs:
      - deploy:
          context: your-context # optional, if you need environment variables
          filters:
            branches:
              only:
                - master # or your default branch
jobs:
  deploy:
    docker:
      - image: cimg/php:8.2.5 # or the PHP version your project requires
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "7f:cc:db:83:e3:ff:55:08:61:0d:ce:07:8b:64:81:d6" # Replace with the fingerprint of your SSH key
      - run:
          name: Install dependencies
          command: composer install --prefer-dist --no-scripts --no-progress --no-interaction
      - run:
          name: Deploy to server
          command: |
            scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./* gabicad_backend_biogames@server1.biogames.hu:/
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null gabicad_backend_biogames@server1.biogames.hu:/ 'cd /web && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force'
