version: 2.1
orbs:
  php: circleci/php@1.0
workflows:
  deploy:
    jobs:
      - deploy:
          context: your-context # optional, if you need environment variables
          filters:
            branches:
              only:
                - master # or your default branch
jobs:
  deploy:
    docker:
      - image: cimg/php:8.2.5 # or the PHP version your project requires
    steps:
      - checkout
      - run:
          name: Install rsync
          command: sudo apt-get update && sudo apt-get install -y rsync
      - add_ssh_keys:
          fingerprints:
            - "b3:80:6a:7f:ae:a5:dc:90:fe:a8:f1:2c:3d:ec:45:da"
      - run:
          name: Install dependencies
          command: composer install --prefer-dist --no-scripts --no-progress --no-interaction
      - run:
          name: Deploy to server (incremental)
          command: |
            rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./ gabicad_backend_biogames@server1.biogames.hu:./web/
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null gabicad_backend_biogames@server1.biogames.hu 'cd ./web/ && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force'
